name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Multi-Architecture Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract repo name
        id: repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.repo.outputs.REPO_NAME }}:latest
            ghcr.io/${{ steps.repo.outputs.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Trigger Portainer Webhook
        run: |
          response=$(curl -s -w "%{http_code}" -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}")
          http_code="${response: -3}"
          if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
            echo "✅ Portainer webhook triggered successfully (HTTP $http_code)"
          else
            echo "❌ Portainer webhook failed (HTTP $http_code)"
            exit 1
          fi
